version : "3"
services:
  api:
    image: examen-cote-serveur-sp-2223:latest
    build:
      -NODE_ENV=production
    ports:
      -"8090":"9090"
    network:
      -node2223sp
    depends_on:
      - mongo
    mongo:
      image: mongo:5
      ports:
        -"8091:27017
      volumes:
        -db
      network:
        node2223sp
volumes:
  db:
networks:
  node2223sp: